import {BrowserProvider,JsonRpcProvider,Contract,ContractFactory,FetchRequest,getAddress,formatUnits,parseUnits} from 'ethers';
import {NETWORKS,COLORS,validateSplit,parseAmount,parseShare,splitAmounts,money,shortAddress,parseOrderLink,makeOrderLink,assertPaymentProof} from './core.mjs';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const saved=(key,fallback=null)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const persist=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
let chain=5042,rows=[{address:'',percent:'70'},{address:'',percent:'30'}],wallet=null,account=null,busy=false,view='create',current=null,contractAddress=null,artifact=null;
let deployments={},loadRevision=0,deployQuote=null;
const providers=new Map(),discovered=[];
const setText=(el,text)=>{el.textContent=text;};
function message(text,error=false){$('message').hidden=!text;$('message').classList.toggle('error',error);$('message').textContent=text||'';}
function errorText(e){if(e?.code==='ACTION_REJECTED'||e?.code===4001)return 'Wallet action cancelled. No automatic retry.';const raw=e?.shortMessage||e?.reason||e?.message||String(e);return raw.length>400?raw.slice(0,400)+'…':raw;}
async function action(button,fn){if(busy)return;busy=true;const controls=[...document.querySelectorAll('button,select')];const prior=controls.map(e=>e.disabled);controls.forEach(e=>e.disabled=true);message('');try{await fn();}catch(e){message(errorText(e),true);}finally{controls.forEach((e,i)=>{if(e.isConnected)e.disabled=prior[i];});busy=false;updateConnect();}}
function updateConnect(){$('connect').textContent=account?shortAddress(account):'Connect wallet';}
function readProvider(c=chain){if(!providers.has(c)){const req=new FetchRequest(NETWORKS[c].rpc);req.timeout=15000;providers.set(c,new JsonRpcProvider(req,c,{staticNetwork:true,batchMaxCount:1,cacheTimeout:-1}));}return providers.get(c);}
async function verifyContract(address,c=chain){if(!artifact)throw new Error('Contract artifact is loading.');const a=getAddress(address);const p=readProvider(c);const actual=Number(BigInt(await p.send('eth_chainId',[])));if(actual!==c)throw new Error('RPC network mismatch.');const code=await p.getCode(a);if(code.toLowerCase()!==artifact.runtime.toLowerCase())throw new Error('This address does not match the original Arc Split contract.');return new Contract(a,artifact.abi,p);}
function setChain(c){if(!NETWORKS[c])throw new Error('Unsupported network');chain=c;$('network').value=String(c);contractAddress=saved(`arc-split-contract-${c}`)||deployments[c]||null;$('contract-address').value=contractAddress||'';$('preview-network').textContent=NETWORKS[c].name;deployQuote=null;$('deploy-review').hidden=true;updateBanner();}
function updateBanner(){const b=$('banner');if(chain===5042002){b.hidden=false;b.textContent='Arc Testnet: test USDC only. These are not mainnet payments.';return;}b.hidden=!!contractAddress||!!current;b.textContent='No mainnet contract is connected. Connect or deploy a contract before creating real payments.';}
function showView(next,{keepOrder=false}={}){loadRevision++;view=next;['create','open','order','setup'].forEach(v=>$(v+'-view').hidden=v!==next);['create','open','setup'].forEach(v=>$('tab-'+v).classList.toggle('active',v===next));if(!keepOrder){current=null;renderPreview();}message('');updateBanner();}
function syncRows(){rows=[...$('recipients').querySelectorAll('.recipient-row')].map(el=>({address:el.querySelector('.address-input').value,percent:el.querySelector('.percent-input').value}));}
function renderRows(){$('recipients').innerHTML=rows.map((r,i)=>`<div class="recipient-row"><span class="recipient-index">0${i+1}</span><label><span class="sr-only">${'Recipient address'} ${i+1}</span><input class="address-input" value="${esc(r.address)}" placeholder="0x…" maxlength="42" spellcheck="false" autocomplete="off" required></label><label class="percent-field"><span class="sr-only">${'Percentage'} ${i+1}</span><input class="percent-input" value="${esc(r.percent)}" inputmode="decimal" maxlength="6" required><span>%</span></label><button class="remove-recipient" type="button" data-index="${i}" ${rows.length<=2?'disabled':''} aria-label="${'Remove recipient'} ${i+1}">×</button></div>`).join('');$('add-recipient').disabled=rows.length>=5;}
function renderPreview(data=null){let amount=0n,shares=rows.map(r=>{try{return parseShare(r.percent);}catch{return 0;}}),addresses=rows.map(r=>r.address),title=$('title').value.trim();try{amount=parseAmount($('amount').value);}catch{}if(data){amount=data.amount;shares=data.shares;addresses=data.recipients;title=data.title;}$('preview-title').textContent=title||'Built together. Paid together.';$('preview-amount').textContent=money(amount);const sum=shares.reduce((a,b)=>a+b,0);$('share-total').textContent=String(sum/100)+'%';$('share-total').classList.toggle('invalid',sum!==10000);const payouts=sum===10000?splitAmounts(amount,shares):shares.map(()=>0n);$('split-bar').innerHTML=shares.map((s,i)=>`<span style="width:${sum?100*s/sum:0}%;background:${COLORS[i]}"></span>`).join('');$('payouts').innerHTML=shares.map((s,i)=>`<div class="payout-item"><span class="payout-dot" style="background:${COLORS[i]}"></span><div class="payout-info"><strong>${'Recipient'} ${i+1}</strong><small>${addresses[i]?esc(shortAddress(addresses[i])):'Add a wallet address'}</small></div><div class="payout-value">${sum===10000?money(payouts[i]):'—'}<small>${s/100}% · USDC</small></div></div>`).join('');const status=$('preview-status');status.className='status';status.textContent='DRAFT';setText($('preview-footnote'),'Preview only · not a payment receipt');}
function formData(){syncRows();return validateSplit({title:$('title').value,amount:$('amount').value.trim(),recipients:rows});}
window.addEventListener('eip6963:announceProvider',event=>{const d=event.detail;if(d?.provider?.request&&!discovered.some(x=>x.info.uuid===d.info?.uuid))discovered.push(d);});window.dispatchEvent(new Event('eip6963:requestProvider'));
async function chooseWallet(){window.dispatchEvent(new Event('eip6963:requestProvider'));if(discovered.length===1)return discovered[0].provider;if(discovered.length>1){return new Promise((resolve,reject)=>{const dialog=document.createElement('dialog');dialog.innerHTML=`<div class="dialog-head"><h2>${'Choose wallet'}</h2><button class="quiet" aria-label="Close">×</button></div>`;for(const item of discovered){const b=document.createElement('button');b.className='secondary wallet-choice';b.textContent=item.info.name;b.onclick=()=>{resolve(item.provider);dialog.close();};dialog.append(b);}dialog.querySelector('.quiet').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{dialog.remove();reject(new Error('Wallet selection cancelled.'));},{once:true});document.body.append(dialog);dialog.showModal();});}if(window.ethereum?.request)return window.ethereum;throw new Error('No wallet detected. Open this page in a browser with an EVM wallet extension such as MetaMask.');}
async function connect(){if(!wallet){wallet=await chooseWallet();wallet.on?.('accountsChanged',accounts=>{account=accounts[0]||null;deployQuote=null;$('deploy-review').hidden=true;updateConnect();});wallet.on?.('chainChanged',()=>{deployQuote=null;$('deploy-review').hidden=true;});}const accounts=await wallet.request({method:'eth_requestAccounts'});if(!accounts?.[0])throw new Error('No wallet account selected');account=getAddress(accounts[0]);updateConnect();return account;}
async function signerFor(c=chain){await connect();const currentChain=Number(BigInt(await wallet.request({method:'eth_chainId'})));if(currentChain!==c){try{await wallet.request({method:'wallet_switchEthereumChain',params:[{chainId:NETWORKS[c].hex}]});}catch(e){if(e.code!==4902)throw e;await wallet.request({method:'wallet_addEthereumChain',params:[{chainId:NETWORKS[c].hex,chainName:NETWORKS[c].name,nativeCurrency:{name:'USDC',symbol:'USDC',decimals:18},rpcUrls:[NETWORKS[c].rpc],blockExplorerUrls:[NETWORKS[c].explorer]}]});await wallet.request({method:'wallet_switchEthereumChain',params:[{chainId:NETWORKS[c].hex}]});}}const active=Number(BigInt(await wallet.request({method:'eth_chainId'})));if(active!==c)throw new Error('Wallet network mismatch');const p=new BrowserProvider(wallet,'any');return p.getSigner();}
async function feeOverrides(c=chain){const price=BigInt(await readProvider(c).send('eth_gasPrice',[]));const floor=parseUnits('20','gwei');return {maxFeePerGas:price*2n>floor?price*2n:floor,maxPriorityFeePerGas:0n};}
async function waitTx(tx){message('Transaction submitted. Waiting for confirmation: '+tx.hash);let receipt;try{receipt=await tx.wait(1,90000);}catch(e){if(e.code==='TRANSACTION_REPLACED'&&!e.cancelled)receipt=e.receipt;else throw e;}if(!receipt||receipt.status!==1)throw new Error('Transaction did not succeed. Check your wallet.');return receipt;}
function eventFrom(receipt,name,address){for(const log of receipt.logs){if(log.address.toLowerCase()!==address.toLowerCase())continue;try{const p=new Contract(address,artifact.abi).interface.parseLog(log);if(p?.name===name)return p;}catch{}}return null;}
async function createOrder(){const data=formData();if(!contractAddress){showView('setup');throw new Error('Deploy or connect a contract before creating an onchain order.');}const address=contractAddress,c=chain;const contract=await verifyContract(address,c);if(data.recipients.some(a=>a.toLowerCase()===address.toLowerCase()))throw new Error('The splitter itself cannot be a recipient.');const signer=await signerFor(c);const tx=await contract.connect(signer).createOrder(data.amount,data.recipients,data.shares,data.title,await feeOverrides(c));const receipt=await waitTx(tx);const ev=eventFrom(receipt,'OrderCreated',address);if(!ev)throw new Error('Missing OrderCreated event');const link=makeOrderLink(location.origin,{chain:c,contract:address,id:String(ev.args.orderId)});history.replaceState(null,'',link);await loadOrder(link);}
function normalizeOrder(raw){return {title:raw.title,amount:raw.amount,recipients:Array.from(raw.recipients),shares:Array.from(raw.shares,Number),creator:raw.creator,paid:raw.paid,paidBy:raw.paidBy,paidBlock:raw.paidBlock};}
async function loadOrder(link){const parsed=parseOrderLink(link);setChain(parsed.chain);showView('order');$('order-view').innerHTML=`<p class="body-copy">${'Reading and verifying the onchain order…'}</p>`;const revision=loadRevision;const contract=await verifyContract(parsed.contract,parsed.chain);const order=normalizeOrder(await contract.getOrder(parsed.id));let proof=null;if(order.paid){const events=await contract.queryFilter(contract.filters.OrderPaid(BigInt(parsed.id)),Number(order.paidBlock),Number(order.paidBlock));if(events.length!==1)throw new Error('Could not confirm the payment event. Try again.');const ev=events[0],receipt=await readProvider(parsed.chain).getTransactionReceipt(ev.transactionHash);assertPaymentProof(order,ev,receipt,parsed.contract,parsed.id);proof={hash:ev.transactionHash,block:receipt.blockNumber,payer:order.paidBy,payouts:splitAmounts(order.amount,order.shares)};}if(revision!==loadRevision)return;current={...order,...parsed,proof};renderOrder();updateBanner();message('');}
function renderOrder(){if(!current)return;const o=current,paid=!!o.proof;renderPreview(o);const st=$('preview-status');st.textContent=paid?'PAID':'AWAITING';st.className='status '+(paid?'paid':'');setText($('preview-footnote'),paid?'Contract event and transaction success verified':'Onchain order · awaiting payment');const payouts=splitAmounts(o.amount,o.shares);$('order-view').innerHTML=`<div class="section-head"><h2>${paid?'Payment receipt':'Review payment'}</h2><span class="step">${paid?'03':'02'} / 03</span></div>${paid?`<div class="paid-heading">Paid · all payouts verified</div>`:''}<p class="body-copy">${esc(o.title)}</p><div class="order-amount">${money(o.amount)} <small>USDC</small></div>${o.recipients.map((a,i)=>`<div class="address-box"><strong>${'Recipient'} ${i+1} · ${o.shares[i]/100}%</strong><p class="mono">${esc(a)}</p><div class="amount-line">${money(payouts[i])} USDC</div></div>`).join('')}<div class="details-list"><span>${'Network'}</span><strong>${esc(NETWORKS[o.chain].name)}</strong><span>${'Order'}</span><strong>${esc(o.id)}</strong><span>${'Creator'}</span><strong class="mono">${esc(o.creator)}</strong><span>${'Contract'}</span><a target="_blank" rel="noopener" href="${NETWORKS[o.chain].explorer}/address/${o.contract}">${esc(o.contract)}</a>${paid?`<span>${'Payer'}</span><strong class="mono">${esc(o.proof.payer)}</strong><span>${'Transaction'}</span><a target="_blank" rel="noopener" href="${NETWORKS[o.chain].explorer}/tx/${o.proof.hash}">${esc(o.proof.hash)}</a>`:''}</div>${!paid?`<p class="receipt-note">${'Check every recipient. Successful payments cannot be reversed through this app. Failed transfers revert the entire payment; network fees can still apply.'}</p><button id="pay" class="primary">Confirm payment in wallet ↗</button>`:`<ul class="receipt-proof"><li>${'Amount matches the immutable order'}</li><li>${'All recipient payouts match'}</li><li>Successful transaction and verified payment event</li></ul>`}<div class="button-row"><button id="copy-order" class="secondary">${paid?'Copy receipt link':'Copy payment link'}</button><button id="refresh-order" class="secondary">${'Refresh status'}</button>${paid?`<button id="download-receipt" class="secondary">${'Download receipt JSON'}</button><button id="print-receipt" class="secondary">${'Print receipt'}</button>`:''}<button id="new-order" class="secondary">${'Create a new split'}</button></div>`;
  $('pay')?.addEventListener('click',()=>action($('pay'),payOrder));$('copy-order')?.addEventListener('click',()=>action($('copy-order'),async()=>{await navigator.clipboard.writeText(makeOrderLink(location.origin,o));message('Link copied.');}));$('refresh-order')?.addEventListener('click',()=>action($('refresh-order'),()=>loadOrder(makeOrderLink(location.origin,o))));$('download-receipt')?.addEventListener('click',downloadReceipt);$('print-receipt')?.addEventListener('click',()=>window.print());$('new-order').onclick=()=>{if(busy)return;history.replaceState(null,'',location.pathname);showView('create');};updateBanner();}
async function payOrder(){const o=current;if(!o)return;const c=await verifyContract(o.contract,o.chain);const fresh=await c.getOrder(o.id);if(fresh.paid){await loadOrder(makeOrderLink(location.origin,o));return;}const signer=await signerFor(o.chain);const fees=await feeOverrides(o.chain);const gas=await c.connect(signer).pay.estimateGas(o.id,{value:fresh.amount,...fees});const signerAddress=await signer.getAddress();const balance=await readProvider(o.chain).getBalance(signerAddress);if(balance<fresh.amount+gas*fees.maxFeePerGas)throw new Error('Insufficient USDC for the payment plus network fees.');const tx=await c.connect(signer).pay(o.id,{value:fresh.amount,...fees});await waitTx(tx);await loadOrder(makeOrderLink(location.origin,o));}
function downloadReceipt(){if(!current?.proof)return;const o=current;const record={app:'Arc Split',version:1,network:NETWORKS[o.chain].name,chainId:o.chain,contract:o.contract,orderId:o.id,title:o.title,totalUSDC:money(o.amount),transactionHash:o.proof.hash||null,payer:o.proof.payer||null,recipients:o.recipients.map((address,i)=>({address,shareBps:o.shares[i],amountUSDC:money(splitAmounts(o.amount,o.shares)[i])})),verification:'Matched original contract runtime, successful receipt, immutable order and payout event',link:makeOrderLink(location.origin,o)};const url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`arc-split-${o.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function estimateDeploy(){if(!artifact)throw new Error('Contract is loading.');const c=chain,signer=await signerFor(c),from=await signer.getAddress(),factory=new ContractFactory(artifact.abi,artifact.bytecode,signer),fees=await feeOverrides(c),req=await factory.getDeployTransaction();const gas=await readProvider(c).estimateGas({...req,from,...fees});deployQuote={chain:c,from};$('deploy-review').hidden=false;$('deploy-review').innerHTML=`<div class="settings-status"><strong>${esc(NETWORKS[c].name)}</strong><p>${'Estimated at the current fee cap'}: ${esc(formatUnits(gas*fees.maxFeePerGas,18))} USDC</p><p class="mono">${esc(from)}</p><p class="help">${'Your wallet shows the final fee. A signed deployment cannot be undone.'}</p></div><button id="deploy" class="primary">${'Confirm deployment in wallet'}</button>`;$('deploy').onclick=()=>action($('deploy'),deployContract);}
async function deployContract(){const q=deployQuote;if(!q||q.chain!==chain)throw new Error('Please estimate the deployment again.');const c=q.chain,signer=await signerFor(c);if((await signer.getAddress()).toLowerCase()!==q.from.toLowerCase())throw new Error('Wallet account changed. Estimate again.');const factory=new ContractFactory(artifact.abi,artifact.bytecode,signer);const deployed=await factory.deploy(await feeOverrides(c));await waitTx(deployed.deploymentTransaction());const addr=await deployed.getAddress();await verifyContract(addr,c);persist(`arc-split-contract-${c}`,addr);contractAddress=addr;$('contract-address').value=addr;$('deploy-review').hidden=true;deployQuote=null;showView('create');message('Contract deployed and verified. You can create a split. Address: '+addr);}
$('connect').onclick=()=>action($('connect'),connect);
$('network').onchange=()=>{if(busy)return;setChain(Number($('network').value));history.replaceState(null,'',location.pathname);showView('create');};
for(const v of ['create','open','setup'])$('tab-'+v).onclick=()=>{if(busy)return;history.replaceState(null,'',location.pathname);showView(v);};
$('recipients').addEventListener('input',()=>{syncRows();renderPreview();});$('recipients').addEventListener('click',e=>{const b=e.target.closest('.remove-recipient');if(!b||busy||rows.length<=2)return;syncRows();rows.splice(Number(b.dataset.index),1);renderRows();renderPreview();});
$('add-recipient').onclick=()=>{if(busy||rows.length>=5)return;syncRows();rows.push({address:'',percent:'0'});renderRows();renderPreview();};
for(const id of ['title','amount'])$(id).addEventListener('input',()=>renderPreview());
$('create-form').onsubmit=e=>{e.preventDefault();action($('create'),createOrder);};
$('open-form').onsubmit=e=>{e.preventDefault();const link=$('payment-link').value.trim();action(e.submitter,async()=>{parseOrderLink(link);await loadOrder(link);if(current)history.replaceState(null,'',makeOrderLink(location.origin,current));});};
$('contract-form').onsubmit=e=>{e.preventDefault();action(e.submitter,async()=>{const c=chain,a=getAddress($('contract-address').value.trim());await verifyContract(a,c);persist(`arc-split-contract-${c}`,a);contractAddress=a;showView('create');message('Contract code verified. You can create a split.');});};
$('estimate-deploy').onclick=()=>action($('estimate-deploy'),estimateDeploy);
window.addEventListener('hashchange',()=>{if(!busy&&location.hash)action(null,()=>loadOrder(location.href));});
function registerTools(){if(!document.modelContext?.registerTool)return;const lifetime=new AbortController();window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});const tools=[{name:'get_split_state',title:'Read split state',description:'Read the current form or order. Does not connect wallets, create orders or send payments.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({view,network:NETWORKS[chain].name,contract:contractAddress,order:current?{id:current.id,paid:!!current.proof,title:current.title,amountUSDC:money(current.amount)}:null})},{name:'prepare_split_request',title:'Prepare split form',description:'Validate and fill the visible split form. This does not create an onchain order, request signatures or send funds. The user must review and click Create.',inputSchema:{type:'object',properties:{title:{type:'string'},amount:{type:'string'},recipients:{type:'array',minItems:2,maxItems:5,items:{type:'object',properties:{address:{type:'string'},percent:{type:'string'}},required:['address','percent'],additionalProperties:false}}},required:['title','amount','recipients'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:input=>{if(busy)throw new Error('Another action is in progress.');const validated=validateSplit(input);showView('create');$('title').value=validated.title;$('amount').value=input.amount;rows=input.recipients.map(r=>({...r}));renderRows();renderPreview();return {prepared:true,onchainOrderCreated:false,amountUSDC:money(validated.amount),recipientCount:rows.length};}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}}}
async function boot(){renderRows();renderPreview();updateConnect();updateBanner();registerTools();try{const responses=await Promise.all([fetch('/contract.json'),fetch('/config.json')]);if(responses.some(r=>!r.ok))throw new Error('Application artifacts could not be loaded.');artifact=await responses[0].json();deployments=(await responses[1].json()).deployments||{};setChain(chain);if(location.hash)await action(null,()=>loadOrder(location.href));}catch(e){message(errorText(e),true);}}
boot();
